name: shoppingapp
description: "A new Flutter project."
publish_to: "none" # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  cloud_firestore: 
  firebase_core: 
  firebase_auth: 
  random_string: ^2.3.1
  shared_preferences: 
  image_picker: 
  firebase_storage: 
  flutter_stripe: 
  http: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
